<?php

// Broadcast Machine Database Configuration File
//cf_dbengine is case sensitive, and must have a corresponding controller in the controller folder that fits the naming convention [dbengine]Controller.php
$cf_dbengine = "Mysql";  		// MySQL = "Mysql", SQLite = "Sqlite" (Duh) 
$cf_hostname = "mysql.gopperman.com";
$cf_username = "bmachine";
$cf_password = "bemacho";
$cf_database = "bmachine";

?>
